name: Java CI/CD

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write   # nécessaire pour créer une release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: spatio-io-lib
          path: target/*.jar